@hostname = localhost
@port = 4040
@object = nhom_loai
@host = {{hostname}}:{{port}}
@endpoint = api/v1/public/{{object}}
@contentType = application/json

### Welcome API Shop Fashion.
GET http://{{host}}/{{endpoint}}/getall HTTP/1.1
Content-Type: {{contentType}}